Upload New Files

diff --git a/AlpineBox b/AlpineBox
--- a/AlpineBox
+++ b/AlpineBox
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 #
 # ┌─────────────────────────────────────────┐
 # │                AlpineBox                │
@@ -21,13 +21,13 @@
 # Author: Mauricio Ferrari
 # License: MIT
 
-VR="1.1"
+VR="1.3"
 
-function _msg_err_no_rootfs
+_msg_err_no_rootfs()
 {
     test -d "$ALPINEBOX_ROOTFS" && return 0
-    echo -e "\033[1A
-==================================================
+    echo \
+"==================================================
 
   Error: rootfs directory not found.
 
@@ -37,37 +37,36 @@ function _msg_err_no_rootfs
   Please run the following command to set it up:
 
  ┌──────────────────────────────────────────────┐
- │                                              │
+ │ $ AlpineBox setup                            │
  └──────────────────────────────────────────────┘
 
-==================================================
-\033[4A │ $ ${0##*/} setup \033[3B"
+=================================================="
 exit 1
 }
 
 
-function _check_deps
+_check_deps()
 {
-    printf "\033[1m"
-    for c in grep links mkdir proot tar rm uname wget
-    {
-        command -v "$c" || echo -e "$c -\033[31m not found\033[0;1m"
+    test "$ALPINEBOX_APPIMAGE" -eq 1 && {
+        echo "Skipping dependency checks: this application is distributed as an AppImage and includes all required libraries."
+        exit 0
     }
-    printf "\033[0m"
+
+    for c in curl find grep gzip mkdir proot tar rm uname
+    do
+        command -v "$c" || echo "$c - not found"
+    done
     exit 0
 }
 
 
-function _check_version
+_check_version()
 {
-    grep -Eo "([0-9]+[.])+[0-9]+" <(
-        grep -Eom1 "alpine-minirootfs-([0-9]+[.])+[0-9]+" <(
-            links -dump "$MIRROR"
-    ))
+    "${E}"curl -s "$MIRROR" | "${E}"grep -Eom1 "alpine-minirootfs-([0-9]+[.])+[0-9]+" | "${E}"grep -Eom1 "([0-9]+[.])+[0-9]+"
 }
 
 
-function _run
+_run()
 {
     _msg_err_no_rootfs
 
@@ -88,36 +87,39 @@ function _run
         --bind=/etc/localtime $PROOT_ARGS
     "
 
-    ALPINEBOX_CMD="${ALPINEBOX_CMD:-${PROGRAM_ARGS[*]}}"
+    ALPINEBOX_CMD="${ALPINEBOX_CMD:-$PROGRAM_ARGS}"
 
-    command proot ${USE_ROOT:+-0} $PROOT_OPTIONS /bin/sh ${ALPINEBOX_CMD:+-c "$ALPINEBOX_CMD"}
+    # shellcheck disable=SC2086
+    "${E}"proot ${USE_ROOT:+-0} $PROOT_OPTIONS /bin/sh ${ALPINEBOX_CMD:+-c "$ALPINEBOX_CMD"}
 }
 
 
-function _update
+_update()
 {
     _msg_err_no_rootfs
 
-    declare -x USE_ROOT=1
-    declare -x ALPINEBOX_CMD="apk update && apk upgrade"
+    USE_ROOT=1
+    ALPINEBOX_CMD="apk update && apk upgrade"
     _run
 }
 
-function _extract_static
+
+_extract_static()
 {
-    declare -x ALPINEBOX_CMD="
+    ALPINEBOX_CMD="
         pkgs=\"\$(apk search $EXTRACT_BINARY.static | grep -Eo \".*-static\")\"
         test -z \"\$pkgs\" || apk add \$pkgs && true
     "
     _run
 
-    find $ALPINEBOX_ROOTFS/usr/{,s}bin -name "$EXTRACT_BINARY.static" -exec cp {} ${EXTRACT_OUTPUT:-.} \;
+    "${E}"find "$ALPINEBOX_ROOTFS"/usr/bin -name "$EXTRACT_BINARY.static" -exec cp {} "${EXTRACT_OUTPUT:-.}" \;
+    "${E}"find "$ALPINEBOX_ROOTFS"/bin -name "$EXTRACT_BINARY.static" -exec cp {} "${EXTRACT_OUTPUT:-.}" \;
 }
 
 
-function _setup
+_setup()
 {
-    (( ALPINEBOX_REINSTALL==1 )) || {
+    test "$ALPINEBOX_REINSTALL" -eq 1 || {
         test -d "$ALPINEBOX_ROOTFS" && {
             echo "Rootfs directory $ALPINEBOX_ROOTFS is already available. Use [-r|--reinstall] to reinstall it."
             exit 0
@@ -130,53 +132,55 @@ function _setup
     TARBALL="alpine-minirootfs-$VERSION-$ARCH.tar.gz"
 
     test -f "$ALPINEBOX_CACHE/$TARBALL" || {
-        rm -rf "$ALPINEBOX_CACHE"
-        mkdir -p "$ALPINEBOX_CACHE"
-        wget -c -P "$ALPINEBOX_CACHE" "$MIRROR/$TARBALL"
+        "${E}"rm -rf "$ALPINEBOX_CACHE"
+        "${E}"mkdir -p "$ALPINEBOX_CACHE"
+
+        cd "$ALPINEBOX_CACHE"
+        "${E}"curl -L -O "$MIRROR/$TARBALL"
+        cd -
     }
     echo "$ALPINEBOX_CACHE/$TARBALL"
 
-    rm -rf "$ALPINEBOX_ROOTFS"
-    mkdir -p "$ALPINEBOX_ROOTFS"
-    tar -xzvf "$ALPINEBOX_CACHE/$TARBALL" -C "$ALPINEBOX_ROOTFS"
+    "${E}"rm -rf "$ALPINEBOX_ROOTFS"
+    "${E}"mkdir -p "$ALPINEBOX_ROOTFS"
+    "${E}"tar -xzvf "$ALPINEBOX_CACHE/$TARBALL" -C "$ALPINEBOX_ROOTFS"
 
     echo "http://dl-cdn.alpinelinux.org/alpine/edge/main
 http://dl-cdn.alpinelinux.org/alpine/edge/community
 http://dl-cdn.alpinelinux.org/alpine/edge/testing
 " > "$ALPINEBOX_ROOTFS/etc/apk/repositories"
 
-    declare -x USE_ROOT=1
+    USE_ROOT=1
     _update
 
-echo -e "\033[1A
-========================================
+echo \
+"========================================
 
   Installation completed successfully!
   To start the environment, run:
 
  ┌────────────────────────────────────┐
- │                                    │
+ │ $ AlpineBox run                    │
  └────────────────────────────────────┘
 
-========================================
-\033[4A │ $ ${0##*/} run \033[3B"
+========================================"
 }
 
 
-function _prepare_dev
+_prepare_dev()
 {
     _update
 
-    declare -x USE_ROOT=1
-    declare -x ALPINEBOX_CMD='apk add alpine-sdk cmake clang'
+    USE_ROOT=1
+    ALPINEBOX_CMD='apk add alpine-sdk cmake clang'
     _run
 }
 
 
-function _print_help
+_print_help()
 {
-echo -e "\033[1A
-┌─────────────────────────────────────────────────────────┐
+echo \
+"┌─────────────────────────────────────────────────────────┐
 │                  AlpineBox Version $VR                  │
 └─────────────────────────────────────────────────────────┘
 
@@ -236,10 +240,10 @@ exit 0
 }
 
 
-function _print_version
+_print_version()
 {
-echo -e "\033[1A
-┌─────────────────────────────────────────────────────────┐
+echo \
+"┌─────────────────────────────────────────────────────────┐
 │                  AlpineBox Version $VR                  │
 └─────────────────────────────────────────────────────────┘
 
@@ -251,32 +255,36 @@ exit 0
 }
 
 
-function _check_essential_parms
+_check_essential_parms()
 {
-    [[ "$1" == "" || (-z $ALLOW_DASH_ARGS && "$1" == -*) ]] && {
+    if [ "$1" = "" ] || { [ -z "$ALLOW_DASH_ARGS" ] && case "$1" in -*) true ;; *) false ;; esac; }; then
         echo "${0##*/}: $2: $3 requires a <$4> as argument."
         echo "Usage: ${0##*/} $2 $3 <$4>"
         exit 1
-    }
+    fi
     return 0
 }
 
 
 set -e
 
-declare -x ARCH="${ARCH:-"$(uname -m)"}"
-declare -x MIRROR="https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/$ARCH"
+ALPINEBOX_APPIMAGE="${ALPINEBOX_APPIMAGE:-0}"
+ALPINEBOX_TOOLS="${ALPINEBOX_TOOLS:-}"
+ALPINEBOX_ROOTFS="${ALPINEBOX_ROOTFS:-"$HOME"/.alpine-rootfs}"
+ALPINEBOX_CACHE="${ALPINEBOX_CACHE:-"$HOME"/.cache/alpine-rootfs}"
+ALPINEBOX_CMD="${ALPINEBOX_CMD:-}"
 
-declare -x ALPINEBOX_ROOTFS="${ALPINEBOX_ROOTFS:-"$HOME"/.alpine-rootfs}"
-declare -x ALPINEBOX_CACHE="${ALPINEBOX_CACHE:-"$HOME"/.cache/alpine-rootfs}"
-declare -x ALPINEBOX_CMD="${ALPINEBOX_CMD:-}"
+E="${ALPINEBOX_TOOLS:+$ALPINEBOX_TOOLS/}"
 
-declare -x CMD=""
-declare -x PROOT_ARGS=""
-declare -x EXTRACT_BINARY=""
-declare -x EXTRACT_OUTPUT=""
-declare -i ALPINEBOX_REINSTALL=0
-declare -a PROGRAM_ARGS=()
+ARCH="${ARCH:-"$("${E}"uname -m)"}"
+MIRROR="https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/$ARCH/"
+
+CMD=""
+PROOT_ARGS=""
+EXTRACT_BINARY=""
+EXTRACT_OUTPUT=""
+ALPINEBOX_REINSTALL=0
+PROGRAM_ARGS=""
 
 for arg in "$@"; do
     case "$arg" in
@@ -314,8 +322,8 @@ done
 
 test -z "$CMD" && CMD="run"
 
-test "$CMD" == "setup" && {
-    while [[ "$#" -gt 0 ]]; do
+test "$CMD" = "setup" && {
+    while [ "$#" -gt 0 ]; do
         case "$1" in
             --cache=*)
                 ALPINEBOX_CACHE="${1#*=}"
@@ -354,22 +362,22 @@ test "$CMD" == "setup" && {
 }
 
 
-test "$CMD" == "run" && {
-    while [[ "$#" -gt 0 ]]; do
+test "$CMD" = "run" && {
+    while [ "$#" -gt 0 ]; do
         case "$1" in
              -0|--root)
-                declare -x USE_ROOT=1
+                USE_ROOT=1
                 shift
                 ;;
             -b|--proot-args)
                 PROOT_ARGS="$2"
-                declare -x ALLOW_DASH_ARGS=1
+                ALLOW_DASH_ARGS=1
                 _check_essential_parms "$PROOT_ARGS" "run" "$1" "proot parameter"
                 shift 2
                 ;;
             --proot-args=*)
                 PROOT_ARGS="${1#*=}"
-                declare -x ALLOW_DASH_ARGS=1
+                ALLOW_DASH_ARGS=1
                 _check_essential_parms "$PROOT_ARGS" "run" "$1" "proot parameter"
                 shift
                 ;;
@@ -384,13 +392,13 @@ test "$CMD" == "run" && {
                 shift
                 ;;
             -c|--command)
-                PROGRAM_ARGS+=("$2")
-                _check_essential_parms "${PROGRAM_ARGS[0]}" "run" "$1" "command"
+                PROGRAM_ARGS="$PROGRAM_ARGS $2"
+                _check_essential_parms "$2" "run" "$1" "command"
                 shift 2
                 ;;
             --command=*)
-                PROGRAM_ARGS+=("${1#*=}")
-                _check_essential_parms "${PROGRAM_ARGS[0]}" "run" "$1" "command"
+                PROGRAM_ARGS="$PROGRAM_ARGS ${1#*=}"
+                _check_essential_parms "${1#*=}" "run" "$1" "command"
                 shift
                 ;;
             --)
@@ -408,14 +416,13 @@ test "$CMD" == "run" && {
         esac
     done
 
-    PROGRAM_ARGS+=("$@")
-    export PROGRAM_ARGS
+    PROGRAM_ARGS="$*"
     _run
     exit 0
 }
 
 
-test "$CMD" == "config" && {
+test "$CMD" = "config" && {
 
     test "$#" -eq 0 && {
         echo "${0##*/}: config: No options provided for 'config'."
@@ -423,10 +430,9 @@ test "$CMD" == "config" && {
         exit 1
     }
 
-    declare -i n=0
-
-    for ((n = 0; n <= $#; n++)); do
-        arg="${!n}"
+    n=0
+    while [ "$n" -le "$#" ]; do
+        eval "arg=\${$n}"
         case "$arg" in
             --directory-rootfs=*)
                 ALPINEBOX_ROOTFS="${arg#*=}"
@@ -434,15 +440,16 @@ test "$CMD" == "config" && {
                 break
                 ;;
             -d|--directory-rootfs)
-                n+=1
-                ALPINEBOX_ROOTFS="${!n}"
+                n=$(( n + 1 ))
+                eval "ALPINEBOX_ROOTFS=\${$n}"
                 _check_essential_parms "$ALPINEBOX_ROOTFS" "config" "$arg" "directory"
                 break
                 ;;
         esac
+        n=$(( n + 1 ))
     done
 
-    while [[ "$#" -gt 0 ]]; do
+    while [ "$#" -gt 0 ]; do
         case "$1" in
             -u|--update)
                 PARM_OK=1
